### PR TITLE
Fix #4150: Correctly outdent ternary followed by method call

### LINKED ISSUE #4150: Possible bug with dot at beginning of line, ternary and object
1.7.0 added "Leading . now closes all open calls, allowing for simpler chaining syntax."

This is great, but I may have just stumbled on a bug with that when using the ternary operator and an object argument.

``` coffee
gulp.task 'stylus', ->
    gulp.src [
        './src/stylus/vars.styl'
        './src/stylus/**/*.styl'
    ]
        .pipe if argv.sourcemaps then require('gulp-sourcemaps').init() else gutil.noop()
        .pipe require('gulp-concat') 'styles.styl'
        .pipe require('gulp-stylus')
            use: require('nib')()
        .pipe if isLocal() then gutil.noop() else require('gulp-minify-css')
            compatibility: '' # Empty string is IE9+ (this is default)
        .pipe if argv.sourcemaps then require('gulp-sourcemaps').write() else gutil.noop()
        .pipe gulp.dest './dist/css'
```

This is coming out as

``` js
// Generated by CoffeeScript 1.9.2
gulp.task('stylus', function() {
  return gulp.src(['./src/stylus/vars.styl', './src/stylus/**/*.styl']).pipe(argv.sourcemaps ? require('gulp-sourcemaps').init() : gutil.noop()).pipe(require('gulp-concat')('styles.styl')).pipe(require('gulp-stylus')({
    use: require('nib')()
  })).pipe(isLocal() ? gutil.noop() : require('gulp-minify-css')({
    compatilibilty: ''
  }).pipe(argv.sourcemaps ? require('gulp-sourcemaps').write() : gutil.noop())).pipe(gulp.dest('./dist/css'));
});
```

I was expecting
- `compatibility: ''` object to be an argument to `require('gulp-minify-css')` -- in this case the result is as expected.
- the dot at the start of the next line to close both the ternary and the `pipe()` from the preceding line -- in this case the result is not as expected: the next `.pipe()` is chained on the end of the `gulp-minify-css` object.

Note that the `gulp-stylus` pipe above also receives an object as an argument but does not have a ternary. This one compiles as I expect.

Note also that the `gulp-sourcemaps` pipes have ternaries but no object argument, and these ones also compile as I expect.

So it seems it's a combination of the tenary and the object argument on a new line.

Is this a bug or am I understanding something incorrectly?

### PR DESCRIPTION
**Pull request by xixixao**
I think the code in #4150 is pretty horrible, and the fact that an inline ternary can continue after a method call in else just seems bizarre. But I do think that:
```coffee
if 0 then 1 else g
  a: 1
.h()
```
should not compile (certainly not as `.h()` being called on the inline object inside the ternary).

So this PR makes it cause a syntax error, as it should. I would guess that implementation-wise this is not the right fix, but it works and I'm not an expert on the `rewriter` logic.

### CODE REVIEW

File: test/formatting.coffee [hunk 1]
```diff
@@ -198,6 +198,27 @@ test "#1495, method call chaining", ->
...
   eq 'a, b, c', result
 
+test "chaining after inline ternary", ->
+  throws -> CoffeeScript.compile """
+    if 0 then 1 else g
+      a: 42
+    .h()
+  """
+
+  # Wrap calls containing spilling ternary
```
Comment (GeoffreyBooth) [inline test/formatting.coffee]: Please put a new line like `test "wrap calls containing spilling ternary", ->` to start a new test.

Currently if anything inside this `test` function fails, the whole test fails and it’s hard to know what part of this failed, since you’re testing multiple things here (the `throws` and the two `eq`s). It would be nice if each of those were separate `test` functions, so that if one of them fails we know exactly which one.

**Comment by GeoffreyBooth** [comment]
While I agree that your example above should throw an error, this shouldn’t:

```coffee
gulp.pipe if 0 then 1 else g
  a: 1
.h()
```

I haven’t tested this, so I don’t know if your version does or doesn’t allow this. We should have a test though that makes sure the above still works as expected (i.e. `gulp` should call `pipe` and then `h`).

File: test/formatting.coffee [hunk 2]
```diff
@@ -198,6 +198,27 @@ test "#1495, method call chaining", ->
...
+  f = (x) -> h: x
+  id = (x) -> x
+  result = f if true then 42 else id
+      a: 2
+  .h
```
Comment (xixixao) [inline test/formatting.coffee]: @GeoffreyBooth I think you missed this test, it's exactly what you asked for.

I will split them each into a separate test call.

Comment (GeoffreyBooth) [inline test/formatting.coffee]: It’s it different between the `gulp.pipe` and `result = f` lines? I agree they’re very similar, and should both work, but I was wondering if the assignment made a difference.

Comment (xixixao) [inline test/formatting.coffee]: Nope, there is no difference. I can add a separate test if you want, but I think as long as this works it should be ok (it's hard to make this pass but your case fail).

**Comment by xixixao** [comment]
@GeoffreyBooth I split up the tests.

**Comment by GeoffreyBooth** [comment]
Thanks. LGTM. @lydell?

**Comment by lydell** [comment]
LGTM
