### PR TITLE
Fix continuing first line of explicit [/{ literal

### LINKED ISSUE #5368: Bug: Destructuring Assignment edge case error
### Input Code

```coffee
{ a
  b: { c }
} = {}
```

### Expected Behavior
Should compile to
```javascript
var a, c;

({
  a,
  b: {c}
} = {});
```

### Current Behavior
```
[stdin]:2:12: error: unexpected }
  b: { c } } = {}
           ^
```

### Work-around
New line after opening brace:

```coffee
{      # New line added here
  a
  b: { c }
} = {}
```

It also works to swap a and b:
```coffee
{ b: { c }
  a
} = {}
```

### Context
This came up for me in the context of passing behavior functions around in a non-trivial object structure.

### Environment

* CoffeeScript version: 2.5.1
* Node.js version: 16.6.2

### PR DESCRIPTION
**Pull request by edemaine**
This PR makes two changes to fix continuing a nonempty first line of an explicit `[` array or `{` object literal:

1. Do not allow implicit call with an implicit object body from first line of `[` array or `{` object literal (as hinted at in comments, but not previously implemented), as in:

   ```coffee
   [x
    y: 2
   ]
   {x
    y: 2
   }
   ```
   Previously, these were treated as function calls where `x` is a function.

2. Support continuing an explicit `{` object literal when the first line has an item on it, as in:

   ```coffee
   {x: 1
    y: 2
   }
   ```
   
   Previously, this was treated as `{x: 1, {y: 2}}` which was invalid.

Fixes #5368

### CODE REVIEW

**Comment by edemaine** [comment]
FYI, I [tried](https://github.com/edemaine/coffeescript/tree/continuing-first-line-2) extending this to handle #5330 also, but that seems substantially harder. 😕

File: src/rewriter.coffee [hunk 1]
```diff
@@ -183,6 +183,7 @@ exports.Rewriter = class Rewriter
       [prevTag] = prevToken = if i > 0 then tokens[i - 1] else []
       [nextTag] = nextToken = if i < tokens.length - 1 then tokens[i + 1] else []
       stackTop  = -> stack[stack.length - 1]
+      stackTop2 = -> stack[stack.length - 2]
```
Comment (GeoffreyBooth) [inline src/rewriter.coffee:186]: A name like `stackTop2` implies to me that it’s returning two elements, not that it’s referring to the second highest item in the stack. Maybe `stackSecond`?

Or maybe do without the helper function? It’s only called in one place, we could just put `stack[stack.length - 2]` there.

**Comment by edemaine** [comment]
Thanks @GeoffreyBooth for the review!
