### PR TITLE
Fix #3933: Missing `then` doesn’t trigger nearby error

### LINKED ISSUE #3933: Lexer: Missing `then` doesn’t trigger nearby error
I was recently trying to compile a syntactically invalid CoffeeScript program, and the resulting compiler error was not as helpful as I'd hoped.  Here's a boiled-down example:

```
% cat test.coffee 
for x in y do ->
  foo()
console.log 'baz'
% coffee test.coffee
test.coffee:3:1: error: unexpected newline
console.log 'baz'
^
% coffee --version
CoffeeScript version 1.9.1
```

The syntax error in `test.coffee` is that it's missing a `then` -- if I instead write `for x in y then do ->` it works fine.

When I first encountered this problem, the loop was quite long and nested, and the error was flagged quite far from where the problem occurred.  I started commenting out lines in the middle of the loop, and started seeing "unexpected indentation" errors attributed to comment lines:

```
% cat test2.coffee                       
do ->
  for x in y do ->
    foo()
#    bar()
#    baz()
console.log 'qux'
% coffee test2.coffee
test2.coffee:5:11: error: unexpected indentation
#    baz()
          ^
```

I found this very surprising, so I figured I'd send a bug report, in case this sort of thing is useful to know about.

### PR DESCRIPTION
**Pull request by zdenko**
Fixes #3933.
`Rewriter::addImplicitBracesAndParens` recognizes code `for a in b do ->` or `for a in b ->` as implicit call. When `then` is missing, `b do ->` and `b ->` are compiled to `b(do ->)` and `b(->)`.

```coffeescript
for a in b do ->
  foo()
  bar()
baz()
```

After `Rewriter`:
```coffeescript
for a in b(do ->
  foo()
  bar())
baz()

# or in a single line

for a in b(do -> foo(); bar())
baz()
```

Other cases:

```coffeescript
for a in b do ->

for a in b ->

while a do ->

while a ->

switch
  when a do ->

switch
  when a ->
```

This PR fixes this by preventing implicit call and enables error to be positioned in correct place.

```coffeescript
for a in b do ->
  foo()

###
error: unexpected do
for a in b do ->
           ^^
###
```

### CODE REVIEW

File: src/rewriter.coffee [hunk 1]
```diff
@@ -263,6 +263,20 @@ exports.Rewriter = class Rewriter
             stack.pop()
         start = stack.pop()
 
+      inControlFlow = =>
+        seenFor = @findTagsBackwards(i, ['FOR']) and @findTagsBackwards(i, ['FORIN', 'FOROF', 'FORFROM'])
+        controlFlow = seenFor or @findTagsBackwards i, ['WHILE', 'UNTIL', 'LOOP', 'LEADING_WHEN']
+        return no unless controlFlow
+        isFunc = no
+        tagCurrentLine = token[2].first_line
+        @detectEnd i,
```
Comment (GeoffreyBooth) [inline src/rewriter.coffee]: Speaking of line continuations, shouldn’t there be a `\` here? I don’t like relying on implicit line continuation.

Comment (zdenko) [reply src/rewriter.coffee]: You mean for these cases
```coffeescript
for a in b \
-> c

for a in b \
do -> c

for \
a \
in \
b \
do \
-> \
```

Comment (vendethiel) [reply src/rewriter.coffee]: we've accepted `,` since basically 2010. It's set to stay now :).

Comment (zdenko) [reply src/rewriter.coffee]: Oh, that one.

Comment (GeoffreyBooth) [reply src/rewriter.coffee]: Fine. 😞

**Comment by GeoffreyBooth** [comment]
@zdenko I know I already merged this, but I just discovered an issue. I can open an issue if you think it warrants it. See dcd6de9a773d834426dbff472349f040bce2d652; after this PR was merged in (I’m pretty sure it was this one, but it might’ve been an earlier one) all `else if`s started to be compiled like `else\nif`:

```coffee
if no
  1
else if yes
  2
```
```js
if (false) {
  1;
} else {
  if (true) {
    2;
  }
}
```

The `else if` [should be output on the same line](http://coffeescript.org/#try:if%20no%0A%091%0Aelse%20if%20yes%0A%092%0A).

**Comment by zdenko** [comment]
I'm working on it.
