### PR TITLE
[CS1] fix #4260 and #1349: splat error with soak properties or expressions

### LINKED ISSUE #4260: Invalid JS: `[a?.b…]` compiles to invalid JavaScript
I found this today, below is the reduced code to reproduce this error on [coffeescript.org](http://coffeescript.org/#try:handler%20%3D%20%28error%29%20%3D%3E%0A%20%20if%20error%20instanceof%20Error%0A%20%20%20%20arr.push%28error%29%0A%20%20else%0A%20%20%20%20arr.push%28error.data%3F.errors...%29%0A%20%20%40showErrors%20%3D%20!!foo.length%0A).

``` coffeescript
handler = (error) =>
  if error instanceof Error
    arr.push(error)
  else
    arr.push(error.data?.errors...)
  @showErrors = !!foo.length
```

``` javascript
var handler;

handler = (function(_this) {
  return function(error) {
    var ref;
    if (error instanceof Error) {
      arr.push(error);
    } else {
      // The loose if-statement is the error
      arr.push.apply(_this,       if ((ref = error.data) != null) {
        ref.errors;
      });
    }
    return _this.showErrors = !!foo.length;
  };
})(this);
```

### PR DESCRIPTION
**Pull request by zdenko**
This is a fix for #4260 and #1349 when invalid JS is compiled if `Splat` contains soak accessor  (`?.`), or `if` statement.

Before:
```javascript
// [a if b...]
slice.call(  if (b) {
    a;
  });

// [a?.b...]
slice.call(  if (typeof a !== "undefined" && a !== null) {
    a.b;
  });

// arr.push(error.data?.errors...)
arr.push.apply(arr, if ((ref = error.data) != null) {
  ref.errors;
});
```

After:
```javascript
// [a if b...]
slice.call((b ? a : void 0));

// [a?.b...]
slice.call((typeof a !== "undefined" && a !== null ? a.b : void 0));

// arr.push(error.data?.errors...)
arr.push.apply(arr, ((ref = error.data) != null ? ref.errors : void 0));
```

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
See #4644. I’m not sure this bug is severe enough that it’s worth fixing in 1.x. Since the current output throws runtime errors, this bug doesn’t cause any bugs in anyone’s code; it’s just that some syntax that should be allowable just isn’t, until #4644 gets merged in. Or to look at it another way, we add support for this syntax in CoffeeScript 2 😄

**Comment by zdenko** [comment]
@GeoffreyBooth `void 0` is the problem. When the `slice` is called the correct output should be:

```javascript
// [a?.b...]
slice.call((typeof a !== "undefined" && a !== null ? a.b : []));
```

I'll take a look.

**Comment by zdenko** [comment]
@GeoffreyBooth I think this should be fixed now.

File: src/nodes.coffee [hunk 1]
```diff
@@ -1812,7 +1812,7 @@ exports.Splat = class Splat extends Base
   assigns: (name) ->
     @name.assigns name
 
-  compileToFragments: (o) ->
+  compileNode: (o) ->
     @name.compileToFragments o
```
Comment (GeoffreyBooth) [inline src/nodes.coffee]: Should this get `LEVEL_OP` too?

Comment (connec) [reply src/nodes.coffee]: In this case no, since in CS1 splats are not operators, but are instead handled by `Arr` and `Assign`.
