### PR TITLE
fix JSX expression indentation bug

### LINKED ISSUE #5055: Bug: reasonable JSX indentation fails
Even though you can use `if` in Coffeescript instead of the canonical-for-standard-JSX `&&`, this is still something people might reasonably want to be able to write, and it currently fails:
```
<div>
  {someCondition &&
    <span />
  }
</div>
```

Will open a fixing PR momentarily

### PR DESCRIPTION
**Pull request by helixbass**
Fixes #5055 

So now eg this compiles:
```
<div>
  {someCondition &&
    <span />
  }
</div>
```

Basically it was choking on the closing empty `INDENT`/`OUTDENT` pair at the end of the parsed tokens inside the nested `{...}` expression

So in `matchWithInterpolations()`, similar to the existing tweaking of `nested` to remove a leading `TERMINATOR`, added a tweaking to remove a closing `INDENT`/`OUTDENT` pair

### CODE REVIEW

File: test/csx.coffee [hunk 1]
```diff
@@ -786,3 +786,16 @@ test 'JSX fragments: fragment with component nodes', ->
...
+    <div>
+      {someCondition &&
+        <span />
+      }
+    </div>
+  ''', '''
+    <div>
+      {someCondition && <span />}
+    </div>;
+  '''
```
Comment (GeoffreyBooth) [inline test/csx.coffee]: How about a test that confirms that this works with a few other types of line continuators, besides just `&&`? And what if the next line is at the same indentation, and what if it’s normal code rather than a CSX tag?

Comment (helixbass) [reply test/csx.coffee]: @GeoffreyBooth sure, added more tests with those variants
