### PR TITLE
Fix #4725: apply transpile option to require’d .coffee files

### LINKED ISSUE #4725: Babel transpilation not working for imported CS files
CS 2.0.1 new Babel transpilation option works well for CS files without other CS files dependencies. But I couldn't make it work  when I have to import a CS file. I have to write the CS file I want to import just like transpilation is not working. For instance:

red.coffee
```coffeescript
import './lib' # working

console.log "lib was imported"
```

lib.coffee
```coffeescript
# chalk = require 'chalk' # working
import chalk from 'chalk' # not working

console.log chalk.red('This is red.')
```

.babelrc
```json
{ "presets": ["env"] }
```

The result is (node 8.6.0):
```shell
$ coffee -t red.coffee 
/home/laurent/nodejs/foo/lib.coffee:2
import chalk from 'chalk';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.loadFile (/home/laurent/nodejs/foo/node_modules/coffeescript/lib/coffeescript/register.js:17:19)
    at Module.load (/home/laurent/nodejs/foo/node_modules/coffeescript/lib/coffeescript/register.js:52:36)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/laurent/nodejs/foo/red.coffee:3:1)
    at Module._compile (module.js:624:30)
    at Object.CoffeeScript.run (/home/laurent/nodejs/foo/node_modules/coffeescript/lib/coffeescript/index.js:61:23)
    at compileScript (/home/laurent/nodejs/foo/node_modules/coffeescript/lib/coffeescript/command.js:264:29)
    at compilePath (/home/laurent/nodejs/foo/node_modules/coffeescript/lib/coffeescript/command.js:219:14)
    at Object.exports.run (/home/laurent/nodejs/foo/node_modules/coffeescript/lib/coffeescript/command.js:140:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffeescript/bin/coffee:15:45)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

I also tried `coffee -t --require babel-register red.coffee`, without effect. Is there something I'm doing wrong?

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Given these two files:

`module.coffee`:
```coffee
import path from 'path'
export getSep = -> path.sep
```
`main.coffee`:
```coffee
import { getSep } from './module.coffee'
console.log getSep()
```

Running `coffee --transpile ./main.coffee` should print `/` (or `\` on Windows). In other words, if the `--transpile` option is specified and we’re transpiling `main.coffee`, we should also transpile any .coffee files it imports. Fixes #4725.

### CODE REVIEW

File: src/index.coffee [hunk 1]
```diff
@@ -104,17 +107,19 @@ if require.extensions
       Use CoffeeScript.register() or require the coffeescript/register module to require #{ext} files.
       """
 
-CoffeeScript._compileFile = (filename, sourceMap = no, inlineMap = no) ->
+CoffeeScript._compileFile = (filename, options = {}) ->
   raw = fs.readFileSync filename, 'utf8'
   # Strip the Unicode byte order mark, if this file begins with one.
   stripped = if raw.charCodeAt(0) is 0xFEFF then raw.substring 1 else raw
 
+  Object.assign options,
```
Comment (lydell) [inline src/index.coffee]: Is mutating `options` intentional here? Or did you mean something like `options = Object.assign {}, options, {stuff}`?

Comment (GeoffreyBooth) [reply src/index.coffee]: What's the difference?

Comment (lydell) [reply src/index.coffee]:
```coffee
myOptions = {foo: true}
CoffeeScript._compileFile "some-file", myOptions
console.log myOptions.filename # "some-file"
```

That `myOptions` has changed after calling `CoffeeScript._compileFile` is a bit unexpected (this is true for any function that takes an `options` object and is a common mistake in JavaScript). Unless you _have_ to mutate `options` for stuff to work, it’s generally better not to do so to avoid bugs further down the road.

Comment (GeoffreyBooth) [reply src/index.coffee]: Fair enough. I was relying on the fact that this is ostensibly a private method, and it’s only called once in our entire codebase; but it can always be safer.

**Comment by GeoffreyBooth** [comment]
Any other notes?
