### PR TITLE
[CS2] Fix handling of parameters that are function calls

### LINKED ISSUE #4406: [CS2] Destructured parameter default evaluation order is broken
Example:

```coffee
current = 0
next    = -> ++current

foo = ({ a = next() }, b = next()) -> [ a, b ]

console.log foo {}
```

Expected output: `[ 1, 2 ]`

Output on `master`: `[ 1, 2 ]`

Output on `2`: `[ 2, 1 ]`

---

This is caused by the `2` branch compiling defaults for simple parameters into the argument list, but handling complex parameters' defaults in the function body.

**Output on `master` (simplified)**

```js
function (arg, b) {
  var a
  a = arg.a != null ? arg.a : next();
  if (b == null) {
    b = next();
  }
  return [a, b];
}
```

**Output on `2` (simplified)**

```js
function (arg, b = next()) {
  var a;
  a = arg.a != null ? arg.a : next();
  return [a, b];
}
```

---

I encountered this whilst improving `super` handling in #4354 (coming soon).

I guess the way we want to fix this is to compile destructured parameters and their defaults to ES also, but I wanted to create an issue to make sure we don't forget about it!

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Fixes #4406. Also revises output of generator functions to be `function*` rather than `function *`, to follow [accepted idiom](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*).

@connec, any notes?

### CODE REVIEW

File: src/nodes.coffee [hunk 1]
```diff
@@ -1945,7 +1945,7 @@ exports.Code = class Code extends Base
       # encountered, add these other parameters to the list to be output in
       # the function definition.
       else
-        if param.isComplex()
+        if param.isComplex() or param.isCall()
```
Comment (lydell) [inline src/nodes.coffee]: So a call does not count as "complex"? What happens if we change `.isComplex()` to also check for calls instead?

Comment (GeoffreyBooth) [inline src/nodes.coffee]: I just couldn’t remember what `isComplex` meant 😄 _But_ I did remember that we documented it [here](https://github.com/jashkenas/coffeescript/wiki/%5BHowTo%5D-How-parsing-works#nodescoffee), which says:
> If `node.isComplex() is false`, it is safe to use `node` more than once. Otherwise you need to store the value of `node` in a variable and output that variable several times instead. Kind of like this: `5` is not complex. `returnFive()` is complex. It’s all about “do we need to cache this expression?”

So there it is—`returnFive()` is exactly our use case. Thanks for the suggestion!

Comment (lydell) [inline src/nodes.coffee]: Nice!

File: src/nodes.coffee [hunk 2]
```diff
@@ -2110,7 +2112,7 @@ exports.Param = class Param extends Base
     @reference = node
 
   isComplex: ->
-    @name.isComplex()
+    @name.isComplex() or (@value? and @value instanceof Call)
```
Comment (connec) [inline src/nodes.coffee]: Bit of a nit-pick but the check for `@value?` is redundant (`@value instanceof Call` doesn't depend on the existence of `@value`).

**Comment by connec** [comment]
Neat fix 👍 made one small change request 😄

**Comment by GeoffreyBooth** [comment]
Thanks @connec, I simplified it. I guess this is ready for merge?

@lydell, how would you feel about renaming `isComplex` to `needsCaching`?

**Comment by lydell** [comment]
> @lydell, how would you feel about renaming `isComplex` to `needsCaching`?

That's a really good idea! However, I'm sure there's one or two places where `.isComplex()` is used to check for something else – perhaps wrongly. If you feel like it, go through each of the 40 occurrences of `isComplex` in nodes.coffee and see if it makes sense.

File: src/nodes.coffee [hunk 3]
```diff
@@ -2110,7 +2112,7 @@ exports.Param = class Param extends Base
     @reference = node
 
   isComplex: ->
-    @name.isComplex()
+    @name.isComplex() or @value instanceof Call
```
Comment (connec) [inline src/nodes.coffee]: Ugh, pity I didn't think of this sooner: this should probably just be `@name.isComplex() or @value.isComplex()`, the following is still broken:

```coffee
i = 0
({ a = ++i }, b = ++i) ->
```

It generates:

```js
// Generated by CoffeeScript 2.0.0-alpha
var i;

i = 0;

(function(arg, b = ++i) { // 'b' will be set first (b === 1)
  var a, ref;
  a = (ref = arg.a) != null ? ref : ++i; // 'a' will be set second (a === 2)
});
```
